name: "Deploy to FTP"
on: push
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout project"
              uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              name: Using node.js to build the project
              with:
                  node-version: '12.x'
                  check-latest: true

            - name: Install dependencies
              run: npm i

            - name: Building
              run: npm run build --prod

#    - name: "Deploy to FTP"
#      uses: SamKirkland/FTP-Deploy-Action@3.1.1
#      with:
#        host: ${{ secrets.HOST }}
#        username: ${{ secrets.USERNAME }}
#        password: ${{ secrets.PASSWORD }}
#        port: ${{ secrets.PORT }}
#        local-dir: game

